baseURL = "https://chopraapooja.github.io"
title = "Pooja Chopra"
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""
Paginate = 5

preserveTaxonomyNames = true

[params]
  description = "All about Pooja Chopra"
  dateFormat = "2006, Jan 2"
  copyrightOwner = "MunifTanjim"
  copyrightStartYear = "2017"
  favicon = "favicon.ico"
  hideEntryNavigation = false
  customCSS = ["css/custom.css"]
  customJS = ["js/custom.js"]
  hideSocialMenu = false
  showReadTime = true

[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"

[params.opengraph]
  [params.opengraph.facebook]
    admins = ""
    appid = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[social]
  facebook = ""

[author]
  name = "Minimo"

[author.social]
  codepen = "chopraapooja"
  email = "chopraapooja@gmail.com"
  facebook = "https://www.facebook.com/pooja.chopra.1213"
  github = "github.com/chopraapooja"
  instagram = "chopraapooja"
  twitter = "chopraapooja"
  linkedin = "chopraapooja"

[permalinks]
  page = "/:slug/"

[[menu.main]]
  name = "Blog"
  weight = -70
  identifier = "chopraapooja"
  url = "https://chopraapooja.github.io"

# Language Configuration
defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
